// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CallbackView: typeof import('./src/components/CallbackView.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./src/components/SafeArea.vue')['default']
    SingleScroll: typeof import('./src/components/SingleScroll.vue')['default']
  }
}

export {}
