export default function initMenuList() {
  return [
    {
      id: '1001',
      name: 'InBox',
      icon: 'icon-menu-inbox',
      path: '/things/inbox',
      type: 'inbox',
      todoList: [],
      color: '#fdd502',
    },
    {
      id: '1002',
      name: 'Today',
      icon: 'icon-menu-today',
      path: '/things/today',
      type: 'today',
      todoList: [],
      color: '#27a2f0',
    },
    {
      id: '1003',
      name: 'UpComming',
      icon: 'icon-menu-upcomming',
      path: '/things/upcomming',
      type: 'upcomming',
      todoList: [],
      color: '#f83470',
    },
    {
      id: '1004',
      name: 'Anytime',
      icon: 'icon-menu-anytime',
      path: '/things/anytime',
      type: 'anytime',
      todoList: [],
      color: '#37a59a',
    },
    {
      id: '1005',
      name: 'Someday',
      icon: 'icon-menu-someday',
      path: '/things/someday',
      type: 'someday',
      todoList: [],
      color: '#cabe86',
    },
    {
      id: '1006',
      name: 'Logbook',
      icon: 'icon-menu-logbook',
      path: '/things/logbook',
      type: 'logbook',
      todoList: [],
      color: '#4abd5e',
    },
  ]
}
